apiVersion: v1
kind: Service
metadata:
  name: kube-service
spec:
  type: NodePort
  selector:
    app: kube-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5500
      nodePort: 30007
